# Generated by Django 2.2.5 on 2019-09-20 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('jira_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('subtask', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('jira_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('jira_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('displayName', models.CharField(max_length=200)),
                ('emailAddress', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='Description')),
                ('jira_id', models.CharField(max_length=200)),
                ('jira_key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Customer')),
                ('jira_users', models.ManyToManyField(to='jira.JiraUser')),
                ('priorities', models.ManyToManyField(to='jira.JiraPriority')),
                ('statuses', models.ManyToManyField(to='jira.JiraStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('jira_id', models.CharField(max_length=200)),
                ('jira_key', models.CharField(max_length=200, unique=True)),
                ('summary', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('environment', models.CharField(max_length=200, null=True)),
                ('duedate', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_to', to='jira.JiraUser')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to='jira.JiraUser')),
                ('issuetype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jira.JiraIssueType')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jira.JiraPriority')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jira.JiraProject')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jira.JiraStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
