# Generated by Django 2.2.5 on 2019-09-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_auto_20190921_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraissue',
            name='jira_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jira.JiraProject'),
        ),
    ]
