# Generated by Django 2.2.5 on 2019-09-30 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0003_auto_20190921_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraissue',
            name='jira_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='jira.JiraProject'),
        ),
    ]
